### ISSUE TITLE
Wrong favicon on tab page

### ISSUE THREAD

**Issue by uilianries** [bincrafters/bincrafters.github.io#1]
When I open the address https://bincrafters.github.io I see the hydejack's favicon on my tab.

![Bincrafters](https://i.imgur.com/3jBDNVT.png)

**Comment by solvingj** [comment]
It’s a cache thing. U visited page before we had the new logo.  Use a diff browser or clear cache to verify.

**Comment by uilianries** [comment]
Oh boy! that was embarrassing!

**Comment by solvingj** [comment]
nonsense, we need other people to provide feedback on the blog. I've found and fixed many embarassing mistakes already.
